export type ProductDetail = {
  slug: string;
  name: string;
  image: string;
  description: string;
  process: string[];
  quantities: string[];
  delivery: string[];
  inquiryEmail: string;
};

export const productDetails: ProductDetail[] = [
  {
    slug: 'chili-powder',
    name: 'Chili Powder',
    image: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=900&q=80',
    description: 'Pure chili powder with vibrant color, balanced heat, and consistent quality for food manufacturing and retail use.',
    process: ['Sun-dried mature chilies', 'Stem removal and cleaning', 'Controlled grinding and sieving', 'Moisture and quality checks', 'Hygienic packaging in export-grade bags'],
    quantities: ['100 g and 250 g retail packs', '1 kg and 5 kg bulk packs', '25 kg export bags'],
    delivery: ['Local delivery within 2-4 business days', 'International air and sea freight', 'Custom packaging and private labeling available'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'cinnamon',
    name: 'Cinnamon',
    image: '/cinnamon-sticks-background.jpg',
    description: 'Premium Ceylon cinnamon sticks and powder with naturally sweet aroma and low coumarin profile.',
    process: ['Hand-harvested cinnamon bark', 'Traditional peeling and quill rolling', 'Natural shade drying', 'Grading by thickness and color', 'Packing under strict hygiene standards'],
    quantities: ['100 g and 500 g packs', '5 kg cartons', '20 kg exporter packs'],
    delivery: ['Domestic delivery in 2-5 business days', 'Export-ready documentation support', 'Temperature-safe shipping options'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'black-pepper',
    name: 'Black Pepper',
    image: '/Black-pepper.jpg',
    description: 'Bold and aromatic black pepper supplied as whole peppercorns or ground powder for culinary and industrial use.',
    process: ['Selective harvest of mature pepper berries', 'Hot-water treatment and drying', 'Machine cleaning and grading', 'Grinding options for powder', 'Final quality inspection and packing'],
    quantities: ['250 g and 1 kg packs', '10 kg food-service bags', '25 kg export sacks'],
    delivery: ['Island-wide courier dispatch', 'Bulk shipment by sea and air', 'Flexible lead times for repeat orders'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'cloves',
    name: 'Cloves',
    image: 'https://images.unsplash.com/photo-1638436462680-1b2b76fbe7fa?w=900&q=80',
    description: 'Aromatic whole cloves with high oil content for spice blends, beverages, and premium food products.',
    process: ['Bud selection at ideal maturity', 'Careful sun drying', 'Sorting and stem removal', 'Aroma and moisture testing', 'Sealed packing for freshness'],
    quantities: ['100 g and 500 g packs', '5 kg cartons', '20 kg export-grade bags'],
    delivery: ['Standard and express local shipping', 'Global delivery via partner logistics', 'Batch-wise dispatch available'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'chilli-flakes',
    name: 'Chilli Flakes',
    image: '/Dried-Chillie-Flakes.jpg',
    description: 'Crushed dried chilli flakes offering strong flavor, vibrant red color, and consistent particle size.',
    process: ['Dry chilli selection', 'Cleaning and de-seeding options', 'Flaking in controlled mills', 'Particle-size grading', 'Moisture-safe packaging'],
    quantities: ['100 g shaker packs', '1 kg food-service packs', '20 kg bulk bags'],
    delivery: ['Doorstep local delivery', 'Export cartons for distributors', 'Private label support for retail brands'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'turmeric',
    name: 'Turmeric',
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=900&q=80',
    description: 'High-curcumin turmeric roots and powder processed for color strength, purity, and stable shelf life.',
    process: ['Rhizome cleaning and boiling', 'Sun/air drying to target moisture', 'Polishing and grading', 'Fine grinding for powder line', 'Laboratory quality verification'],
    quantities: ['250 g and 1 kg pouches', '5 kg cartons', '25 kg industrial bags'],
    delivery: ['Local supply for wholesale and retail', 'International shipping with compliance docs', 'Scheduled dispatch for contracts'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'cardamom',
    name: 'Cardamom',
    image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=900&q=80',
    description: 'Green cardamom pods with premium aroma and clean appearance for tea blends, desserts, and spice mixes.',
    process: ['Hand-picked green pods', 'Controlled low-temperature drying', 'Size and color sorting', 'Aroma retention packaging', 'Final quality approval'],
    quantities: ['100 g and 500 g packs', '2 kg and 5 kg bulk packs', '15 kg export cartons'],
    delivery: ['Fast local delivery', 'Air cargo for freshness-sensitive markets', 'Retail and wholesale dispatch options'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'dried-herbs',
    name: 'Dried Herbs',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
    description: 'Clean and carefully dried herbs retaining natural aroma and active compounds for food and wellness use.',
    process: ['Fresh herb sourcing', 'Low-heat drying cycle', 'Cutting and sorting', 'Contaminant screening', 'Sealed food-safe packaging'],
    quantities: ['100 g packs', '1 kg packs', '10 kg wholesale cartons'],
    delivery: ['Nationwide courier', 'Global shipping with secure packaging', 'Recurring shipment schedules available'],
    inquiryEmail: 'support@lankoraagro.com',
  },
  {
    slug: 'herbal-teas',
    name: 'Herbal Teas',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=900&q=80',
    description: 'Naturally blended herbal teas for wellness and flavor, ideal for retail and hospitality sectors.',
    process: ['Herb selection and cleaning', 'Blend formulation by profile', 'Cut and sieve consistency checks', 'Microbial and moisture testing', 'Packing in tea-safe pouches'],
    quantities: ['20-bag and 50-bag retail boxes', '1 kg loose blends', '10 kg hospitality packs'],
    delivery: ['2-5 day local dispatch', 'Global delivery with customs support', 'Brand-ready white label options'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'tea',
    name: 'Tea',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=900&q=80',
    description: 'Loose-leaf tea selected for briskness, aroma, and consistent cup color across grades.',
    process: ['Leaf plucking and sorting', 'Withering and rolling', 'Oxidation and drying', 'Grade separation', 'Moisture-protected packing'],
    quantities: ['100 g and 500 g retail pouches', '5 kg and 20 kg bulk bags', 'Custom private label quantities'],
    delivery: ['Quick domestic distribution', 'Global sea and air freight', 'Shipment tracking provided for all orders'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'tea-bags',
    name: 'Tea Bags',
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=900&q=80',
    description: 'Convenient tea bags with consistent infusion quality for home, office, and hospitality use.',
    process: ['Tea blending and dosing', 'Automated bagging and sealing', 'Thread/tag quality checks', 'Cartoning and coding', 'Final batch inspection'],
    quantities: ['25, 50, and 100 bag cartons', 'Hospitality packs of 500 bags', 'Private label tea bag programs'],
    delivery: ['Local and regional wholesale distribution', 'International pallet shipping', 'Recurring monthly supply options'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'aroma-products',
    name: 'Aroma Products',
    image: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f2e2?w=900&q=80',
    description: 'Natural aromatic products designed for personal care, home care, and wellness applications.',
    process: ['Raw botanical extraction', 'Blending and standardization', 'Stability checks', 'Scent consistency testing', 'Leak-proof packaging'],
    quantities: ['50 ml and 100 ml retail units', '1 L and 5 L commercial packs', 'Bulk supply on request'],
    delivery: ['Secure domestic delivery', 'International DG-compliant options where required', 'Distributor-ready cartons'],
    inquiryEmail: 'support@lankoraagro.com',
  },
  {
    slug: 'grains',
    name: 'Grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=900&q=80',
    description: 'Quality grains including rice, wheat, and cereals processed for food-grade consistency and shelf stability.',
    process: ['Farm sourcing and intake testing', 'Cleaning and grading', 'Polishing/milling options', 'Foreign matter control', 'Bulk and retail packaging'],
    quantities: ['1 kg and 5 kg packs', '25 kg and 50 kg sacks', 'Container-load supply'],
    delivery: ['Domestic wholesale routes', 'Port-to-port export logistics', 'Planned delivery windows for contracts'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'seeds',
    name: 'Seeds',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=900&q=80',
    description: 'High-quality seeds for cultivation, oil extraction, and food applications with reliable purity levels.',
    process: ['Seed selection and cleaning', 'Drying and grading', 'Purity and germination testing', 'Moisture control', 'Export-quality packing'],
    quantities: ['500 g and 1 kg packs', '10 kg and 25 kg bags', 'Custom bulk quantities'],
    delivery: ['Nationwide dispatch', 'International cargo options', 'Documentation assistance for importers'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'pulses',
    name: 'Pulses',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=900&q=80',
    description: 'Nutritious pulses and legumes graded for cooking quality, clean appearance, and supply consistency.',
    process: ['Sorting and destoning', 'Color and size grading', 'Dust and impurity removal', 'Quality and moisture checks', 'Retail/bulk packaging'],
    quantities: ['1 kg and 5 kg packs', '25 kg sacks', 'Bulk commodity volumes available'],
    delivery: ['Direct local distribution', 'Bulk export fulfillment', 'Contract-based monthly dispatch'],
    inquiryEmail: 'sales@lankoraagro.com',
  },
  {
    slug: 'oils-and-extracts',
    name: 'Oils & Extracts',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=900&q=80',
    description: 'Pure oils and botanical extracts for food, cosmetic, and wellness formulations.',
    process: ['Raw material preparation', 'Cold press/steam extraction', 'Filtration and refinement', 'Purity and profile testing', 'Tamper-proof filling'],
    quantities: ['100 ml and 250 ml bottles', '1 L and 5 L canisters', 'Industrial bulk options'],
    delivery: ['Protective packaging for leakage control', 'Local and export logistics', 'Repeat shipment programs available'],
    inquiryEmail: 'support@lankoraagro.com',
  },
  {
    slug: 'health-supplements',
    name: 'Health Supplements',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=900&q=80',
    description: 'Natural health supplement products prepared under strict quality standards for modern wellness needs.',
    process: ['Ingredient sourcing and validation', 'Blending and dosage control', 'Stability and safety checks', 'Batch coding and traceability', 'Compliance-focused packaging'],
    quantities: ['30 and 60 count retail packs', 'Clinic and pharmacy bulk packs', 'Custom private label runs'],
    delivery: ['Retail-ready domestic supply', 'International dispatch options', 'Distributor and partner channel fulfillment'],
    inquiryEmail: 'support@lankoraagro.com',
  },
];

export function getProductDetail(slug: string): ProductDetail | undefined {
  return productDetails.find((product) => product.slug === slug);
}
